apiVersion: v1
kind: Namespace
metadata:
  name: simple-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-simple-nginx
  namespace: simple-nginx
  labels:
    app: simple-nginx
    tier: demo
spec:
  selector:
    matchLabels:
      app: simple-nginx
      tier: demo
  replicas: 4
  template:
    metadata:
      labels:
        app: simple-nginx
        tier: demo
    spec:
      containers:
      - name: fleet-simple-nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-nginx
    tier: demo
  name: fleet-simple-nginx
  namespace: simple-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: simple-nginx
    tier: demo
  type: NodePort

